### ISSUE TITLE
[landing] Landing on certain urls doesn't work

### ISSUE THREAD

**Issue by youzi** [vigour-io/url#9] opened 2016-03-03 16:03 UTC
eg. <host>/shows/2091:Dubai-Lynx/2167:2015-Winners/3848:HEY-FUTURE-ME...

**Comment by marcusbesjes** [comment] 2016-03-07 14:04
This was caused by the periods (...) in the url, fixed now by modifying the url generator

**Closed by marcusbesjes** 2016-03-07 14:04 UTC
